packages:
  - apps/*
allowBuilds:
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@next/env@16.3.7'
  - '@next/eslint-plugin-next@16.3.7'
  - '@next/swc-darwin-arm64@16.3.7'
  - '@next/swc-darwin-x64@16.3.7'
  - '@next/swc-linux-arm64-gnu@16.3.7'
  - '@next/swc-linux-arm64-musl@16.3.7'
  - '@next/swc-linux-x64-gnu@16.3.7'
  - '@next/swc-linux-x64-musl@16.3.7'
  - '@next/swc-win32-arm64-msvc@16.3.7'
  - '@next/swc-win32-x64-msvc@16.3.7'
  - eslint-config-next@16.3.7
  - next@16.3.7
  - '@sentry/browser-utils@11.2.0'
  - '@sentry/browser@11.2.0'
  - '@sentry/bundler-plugins@11.2.0'
  - '@sentry/core@11.2.0'
  - '@sentry/feedback@11.2.0'
  - '@sentry/nextjs@11.2.0'
  - '@sentry/node@11.2.0'
  - '@sentry/opentelemetry@11.2.0'
  - '@sentry/react@11.2.0'
  - '@sentry/replay-canvas@11.2.0'
  - '@sentry/replay@11.2.0'
  - '@sentry/server-runtime-injection@11.2.0'
  - '@sentry/server-utils@11.2.0'
  - '@sentry/vercel-edge@11.2.0'
