import {test} from 'node:test';
import assert from 'node:assert/strict';
import {setTimeout} from 'node:timers/promises';
import {sandbox,root} from '../scripts/local-sandbox.mjs';
import {schedulerLab} from '../scripts/scheduler-lab.mjs';
import {readFile} from 'node:fs/promises';
const current=process.env.NGAJITRACK_TEST_SCHEMA_VERSION==='11';
import {makeFixture} from './fixture.mjs';
async function context(fn){const s=await (current?schedulerLab():sandbox());let upgraded=false;const clients=[];try{const f=await makeFixture(s);async function actor(name){if(current&&!upgraded){
 for(const file of ['20260925000800_expiry_scheduler.sql','20260925000900_enrollment_approvals.sql','20260925001000_verified_provisioning.sql','20260926001100_academic_governance.sql'])await s.query(await readFile(new URL('supabase/migrations/'+file,root),'utf8'));
 await s.query('select cron.alter_job(jobid,active:=false) from cron.job');upgraded=true;
 }const c=await s.connect();clients.push(c);await c.query('begin');if(name){await c.query("select set_config('request.jwt.claim.sub',$1,true)",[f.users[name]]);await c.query('set local role authenticated');}else await c.query(current?'set local role ngt_expiry_scheduler':'set local role service_role');return c;}await fn(s,f,actor);}finally{for(const c of clients){await c.query('rollback').catch(()=>{});await c.end();}await s.close();}}
async function blocked(s,c){const deadline=Date.now()+3000;while(Date.now()<deadline){const r=await s.query("select wait_event_type from pg_stat_activity where pid=$1",[c.processID]);if(r.rows[0]?.wait_event_type==='Lock')return;await setTimeout(10);}throw Error('Expected overlapping transactions waiting on a database lock');}
const close=(c,id)=>c.query('select public.end_institution_enrollment($1)',[id]);
const expire=c=>c.query('select public.expire_institution_enrollments(1) n');
async function endedOnce(s,id){assert.equal((await s.query('select status from public.institution_enrollments where id=$1',[id])).rows[0].status,'ENDED');assert.equal((await s.query("select count(*)::int n from public.audit_logs where entity_id=$1 and action='UPDATE' and new_value->>'status'='ENDED'",[id])).rows[0].n,1);assert.equal((await s.query("select count(*)::int n from public.program_enrollments where institution_enrollment_id=$1 and status in ('ACTIVE','PENDING')",[id])).rows[0].n,0);}
test('two workers claim distinct locked batches with no duplicate closure',()=>context(async(s,f,actor)=>{await s.query("update public.institution_enrollments set enrollment_type='HOLIDAY',scheduled_end_at=current_date where id=any($1::uuid[])",[[f.ie.a1.id,f.ie.b1.id]]);const a=await actor(),b=await actor();assert.equal((await expire(a)).rows[0].n,1);assert.equal((await expire(b)).rows[0].n,1);await b.query('commit');await a.query('commit');await endedOnce(s,f.ie.a1.id);await endedOnce(s,f.ie.b1.id);}));
test('manual closure holds root while worker skips it; unrelated tenant remains active',()=>context(async(s,f,actor)=>{await s.query("update public.institution_enrollments set enrollment_type='TEMPORARY',scheduled_end_at=current_date where id=$1",[f.ie.a1.id]);const a=await actor('adminA'),b=await actor();await close(a,f.ie.a1.id);assert.equal((await expire(b)).rows[0].n,0);await b.query('commit');await a.query('commit');await endedOnce(s,f.ie.a1.id);assert.equal((await s.query('select status from public.institution_enrollments where id=$1',[f.ie.b1.id])).rows[0].status,'ACTIVE');}));
test('manual closure waits for worker then returns idempotently',()=>context(async(s,f,actor)=>{await s.query("update public.institution_enrollments set enrollment_type='TEMPORARY',scheduled_end_at=current_date where id=$1",[f.ie.a1.id]);const a=await actor(),b=await actor('adminA');await expire(a);const pending=close(b,f.ie.a1.id);await blocked(s,b);await a.query('commit');await pending;await b.query('commit');await endedOnce(s,f.ie.a1.id);}));
test('two administrators closing the same enrollment produce one audit closure',()=>context(async(s,f,actor)=>{const a=await actor('adminA'),b=await actor('adminA');await close(a,f.ie.a1.id);const pending=close(b,f.ie.a1.id);await blocked(s,b);await a.query('commit');await pending;await b.query('commit');await endedOnce(s,f.ie.a1.id);}));
test('class move waits for closure and cannot reopen ended placements',()=>context(async(s,f,actor)=>{const a=await actor('adminA'),b=await actor('adminA');await close(a,f.ie.a1.id);const pending=b.query('select public.move_student_group($1,$2)',[f.pe.a1.id,f.groups.a2.id]).then(()=>null,e=>e.code);await blocked(s,b);await a.query('commit');assert.equal(await pending,'23514');await b.query('rollback');await endedOnce(s,f.ie.a1.id);}));
test('closure waits for an in-flight class move then closes its new placement',()=>context(async(s,f,actor)=>{const a=await actor('adminA'),b=await actor('adminA');await a.query('select public.move_student_group($1,$2)',[f.pe.a1.id,f.groups.a2.id]);const pending=close(b,f.ie.a1.id);await blocked(s,b);await a.query('commit');await pending;await b.query('commit');await endedOnce(s,f.ie.a1.id);assert.equal((await s.query("select count(*)::int n from public.group_memberships where program_enrollment_id=$1 and status='ACTIVE'",[f.pe.a1.id])).rows[0].n,0);}));
